webapp/config/routes.rb
Rails.application.routes.draw do
  root              to: "family_members#index"
  get "/:id",       to: "family_members#show", as: :family_member
  post "/triggers", to: "triggers#create"
end

webapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

webapp/app/models/family_member.rb
class FamilyMember < ApplicationRecord
  has_many :triggers

  def to_s
    name
  end
end

webapp/app/models/trigger.rb
class Trigger < ApplicationRecord
  belongs_to :family_member
end

webapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

webapp/app/controllers/family_members_controller.rb
class FamilyMembersController < ApplicationController
  def show
    @family_member = FamilyMember.find(params[:id])
  end
end

webapp/app/controllers/triggers_controller.rb
class TriggersController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def create
    if family_member = FamilyMember.find_by(device_id: params[:coreid])
      family_members.triggers.create(color: pparams[:color])

      # TODO: send triggers to
    end
  end

  private

  def pparams
    params.permit!
  end
end

webapp/app/helpers/application_helper.rb
module ApplicationHelper
end

webapp/app/views/family_members/index.html.erb
<ul>
  <% FamilyMember.order(:blink_id).each do |family_member| %>
    <li><%= link_to family_member, family_member_path(family_member) %></li>
  <% end %>
</ul>

webapp/app/views/family_members/show.html.erb
<%= link_to "< Back", root_url %>

<h1><%= @family_member %></h1>

webapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Familamp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>